global:
  checkNewVersion: true
  sendAnonymousUsage: false  # true by default

# (Optional) Enable API and Dashboard
# ---
api:
  dashboard: ${ENABLE_TRAEFIK_DASHBOARD:-false}
  insecure: ${ENABLE_TRAEFIK_DASHBOARD:-false}

# Entry Points configuration
# ---
entryPoints:
  web:
    address: :80
    # (Optional) Redirect to HTTPS
    # ---
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: :443

# Configure your CertificateResolver here...
# ---
certificatesResolvers:
  staging:
    acme:
      email: ${EMAIL}
      storage: /etc/traefik/certs/acme.json
      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      tlsChallenge: {}
      httpChallenge:
        entryPoint: web

  production:
    acme:
      email: ${EMAIL}
      storage: /etc/traefik/certs/acme.json
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
      tlsChallenge: {}
      httpChallenge:
        entryPoint: web

  cloudflare:
    acme:
      email: ${EMAIL}
      storage: /etc/traefik/certs/acme.json
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
      dnsChallenge:
        provider: cloudflare
        # Cloudflare credentials are provided via environment variables in docker-compose.yml:
        # - CF_API_EMAIL
        # - CF_DNS_API_TOKEN

providers:
  docker:
    exposedByDefault: false  # Default is true
  swarm:
  file:
    # watch for dynamic configuration changes
    directory: /etc/traefik
    watch: true