services:

  # Traefik
  # ---
  # Traefik is a modern HTTP reverse proxy and load balancer that makes deploying microservices easy.
  # It supports several backends (Docker, Swarm, Kubernetes, Marathon, Consul, Etcd, Rancher, Amazon ECS, and a lot more) to manage its configuration automatically and dynamically.
  # https://traefik.io/
  traefik:
    container_name: "traefik"
    image: "traefik:v3.2"
    ports:
      - "80:80"
      - "443:443"
      # Only expose dashboard port if enabled
      - "${TRAEFIK_DASHBOARD_PORT:-8080}:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - traefik-ssl-certs:/ssl-certs
      - ./traefik:/etc/traefik
    networks:
      - traefik_network
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    environment:
      - TZ=${TZ:-Africa/Dar_es_Salaam}
      - CF_API_EMAIL=${CF_API_EMAIL:-"no-email@no-host"}
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN:-"no-api-token"}

  # Portainer
  # ---
  # Portainer is a lightweight management UI which allows you to easily manage your Docker host or Swarm cluster.
  # https://www.portainer.io/
  portainer:
    container_name: portainer
    image: "docker.io/portainer/portainer-ce:2.21.4"
    ports:
      - "${PORTAINER_PORT:-9000}:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    networks:
      - traefik_network
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`${PORTAINER_DOMAIN}`)"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
      - "traefik.http.routers.portainer.tls.certresolver=production"
    # Only start Portainer with these profiles
    profiles:
      - "portainer"
      - "ui"
      - "all"

  # Watchtower
  # ---
  # Watchtower is a process for automating Docker container base image updates.
  # https://containrrr.dev/watchtower/
  watchtower:
    container_name: "watchtower"
    image: "docker.io/containrrr/watchtower"
    volumes:
       - /var/run/docker.sock:/var/run/docker.sock
       - /root/.docker/config.json:/config.json:ro
    restart: always
    environment:
      - TZ=${TZ:-Africa/Dar_es_Salaam}
      - WATCHTOWER_LIFECYCLE_HOOKS=1
    command: --debug --cleanup --interval 60 # 1 minute
    # Include in maintenance profile
    profiles:
      - "maintenance"
      - "all"

networks:
  traefik_network:
    external: true

volumes:
  portainer-data:
  traefik-ssl-certs:
