name: Release Docker Setup Tool

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set version from tag
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
          echo "Building version ${GITHUB_REF#refs/tags/v}"

      - name: Make build script executable
        run: |
          chmod +x build.sh
          chmod +x src/*.sh

      - name: Build package
        run: bash build.sh ${{ env.VERSION }}

      - name: Generate changelog
        run: |
          echo "## What's Changed" > changelog.md
          git log $(git describe --tags --abbrev=0 HEAD^)..HEAD --pretty=format:"* %s" >> changelog.md

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/docker-setup-${{ env.VERSION }}.tar.gz
            dist/docker-setup-${{ env.VERSION }}.tar.gz.sha256
          body_path: changelog.md
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
