name: Build test for Docker Setup Tool

on:
  push:
    tags:
      - 'main'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set version from tag
        run: |
          echo "VERSION=0.1.0" >> $GITHUB_ENV
          echo "Building version 0.1.0"

      - name: Make build script executable
        run: |
          chmod +x build.sh
          chmod +x src/*.sh

      - name: Build package
        run: bash build.sh ${{ env.VERSION }}

      